name: C/C++ CI

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Preparation on Linux
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install libasound2-dev libcurl4-openssl-dev libwebkit2gtk-4.0-dev

    - name: Preparation on Windows
      if: runner.os == 'Windows'
      uses: microsoft/setup-msbuild@v1.1

    - name: Build libraries
      run: |
        cmake -B build_debug -DCMAKE_BUILD_TYPE=Debug
        cmake --build build_debug --config Debug
        cmake -B build_release -DCMAKE_BUILD_TYPE=Release
        cmake --build build_release --config Release

    - name: Test
      run: |
        pushd build_debug
        ctest -C Debug -VV
        popd
        pushd build_release
        ctest -C Release -VV
        popd

    - name: Build plugins
      run: |
        pushd plugins/00Template
        cmake -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build --config Release
        popd
        pushd plugins/AE2SimpleConvolver
        cmake -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build --config Release
        popd
        pushd plugins/AE2Distortion
        cmake -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build --config Release
        popd
        pushd plugins/AE2SpectrumAnalyzer
        cmake -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build --config Release
        popd
        pushd plugins/AE2NBandsEqualizer
        cmake -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build --config Release
        popd
        pushd plugins/AE2Pannner
        cmake -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build --config Release
        popd

    - name: Create artifacts on UNIX platform
      if: runner.os == 'Linux' || runner.os == 'macOS'
      run: |
        ARTIFACT_ROOT=artifact_${{ matrix.os }}
        mkdir ${ARTIFACT_ROOT} 
        pushd ${ARTIFACT_ROOT}
        mkdir plugins
        popd
        cp -r plugins/AE2SimpleConvolver/build/AE2SimpleConvolver_artefacts/Release/VST3 ${ARTIFACT_ROOT}/plugins/
        cp -r plugins/AE2SimpleConvolver/build/AE2SimpleConvolver_artefacts/Release/Standalone ${ARTIFACT_ROOT}/plugins/
        cp -r plugins/AE2Distortion/build/AE2Distortion_artefacts/Release/VST3 ${ARTIFACT_ROOT}/plugins/
        cp -r plugins/AE2Distortion/build/AE2Distortion_artefacts/Release/Standalone ${ARTIFACT_ROOT}/plugins/
        cp -r plugins/AE2SpectrumAnalyzer/build/AE2SpectrumAnalyzer_artefacts/Release/VST3 ${ARTIFACT_ROOT}/plugins/
        cp -r plugins/AE2SpectrumAnalyzer/build/AE2SpectrumAnalyzer_artefacts/Release/Standalone ${ARTIFACT_ROOT}/plugins/
        cp -r plugins/AE2NBandsEqualizer/build/AE2NBandsEqualizer_artefacts/Release/VST3 ${ARTIFACT_ROOT}/plugins/
        cp -r plugins/AE2NBandsEqualizer/build/AE2NBandsEqualizer_artefacts/Release/Standalone ${ARTIFACT_ROOT}/plugins/
        cp -r plugins/AE2NBandsEqualizer/build/AE2Pannner_artefacts/Release/VST3 ${ARTIFACT_ROOT}/plugins/
        cp -r plugins/AE2NBandsEqualizer/build/AE2Pannner_artefacts/Release/Standalone ${ARTIFACT_ROOT}/plugins/
        tar -czf ${ARTIFACT_ROOT}.tar.gz ${ARTIFACT_ROOT} 

    - name: Create artifacts on Windows platform
      if: runner.os == 'Windows'
      shell: powershell
      run: |
        $ARTIFACT_ROOT = "artifact_${{ matrix.os }}"
        mkdir ${ARTIFACT_ROOT} 
        pushd ${ARTIFACT_ROOT}
        mkdir plugins
        popd
        Copy-Item plugins/AE2SimpleConvolver/build/AE2SimpleConvolver_artefacts/Release/VST3 ${ARTIFACT_ROOT}/plugins/ -Recurse -Force
        Copy-Item plugins/AE2SimpleConvolver/build/AE2SimpleConvolver_artefacts/Release/Standalone ${ARTIFACT_ROOT}/plugins/ -Recurse -Force
        Copy-Item plugins/AE2Distortion/build/AE2Distortion_artefacts/Release/VST3 ${ARTIFACT_ROOT}/plugins/ -Recurse -Force
        Copy-Item plugins/AE2Distortion/build/AE2Distortion_artefacts/Release/Standalone ${ARTIFACT_ROOT}/plugins/ -Recurse -Force
        Copy-Item plugins/AE2SpectrumAnalyzer/build/AE2SpectrumAnalyzer_artefacts/Release/VST3 ${ARTIFACT_ROOT}/plugins/ -Recurse -Force
        Copy-Item plugins/AE2SpectrumAnalyzer/build/AE2SpectrumAnalyzer_artefacts/Release/Standalone ${ARTIFACT_ROOT}/plugins/ -Recurse -Force
        Copy-Item plugins/AE2NBandsEqualizer/build/AE2NBandsEqualizer_artefacts/Release/VST3 ${ARTIFACT_ROOT}/plugins/ -Recurse -Force
        Copy-Item plugins/AE2NBandsEqualizer/build/AE2NBandsEqualizer_artefacts/Release/Standalone ${ARTIFACT_ROOT}/plugins/ -Recurse -Force
        Copy-Item plugins/AE2NBandsEqualizer/build/AE2Pannner_artefacts/Release/VST3 ${ARTIFACT_ROOT}/plugins/ -Recurse -Force
        Copy-Item plugins/AE2NBandsEqualizer/build/AE2Pannner_artefacts/Release/Standalone ${ARTIFACT_ROOT}/plugins/ -Recurse -Force
        tar -czf "${ARTIFACT_ROOT}.tar.gz" ${ARTIFACT_ROOT} 

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: |
          artifact_${{ matrix.os }}.tar.gz
